<?php

namespace Lthrt\EntityBundle\Tests\Entity;

trait TestEntitySqlTrait
{
    protected static $sql = [
        "CREATE TABLE test_entity7 (id INTEGER NOT NULL, field VARCHAR(255) DEFAULT NULL, otherfield VARCHAR(255) DEFAULT NULL, _field VARCHAR(255) DEFAULT NULL, date_field DATE DEFAULT NULL, PRIMARY KEY(id));",
        "CREATE TABLE test_entity1 (id INTEGER NOT NULL, extra_fluff VARCHAR(60) DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE test_entity9 (id INTEGER NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE nine__eight (nine_id INTEGER NOT NULL, eight_id INTEGER NOT NULL, PRIMARY KEY(nine_id, eight_id));",
        "CREATE INDEX IDX_C0103D66DAE4646B ON nine__eight (nine_id);",
        "CREATE INDEX IDX_C0103D6622E95007 ON nine__eight (eight_id);",
        "CREATE TABLE test_entity11 (id INTEGER NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE test_entity5 (id INTEGER NOT NULL, field VARCHAR(255) DEFAULT NULL, otherfield VARCHAR(255) DEFAULT NULL, _field VARCHAR(255) DEFAULT NULL, date_field DATE DEFAULT NULL, PRIMARY KEY(id));",
        "CREATE TABLE test_entity8 (id INTEGER NOT NULL, seven_id INTEGER DEFAULT NULL, badseven_id INTEGER DEFAULT NULL, PRIMARY KEY(id));",
        "CREATE INDEX IDX_652642F55023A0AB ON test_entity8 (seven_id);",
        "CREATE INDEX IDX_652642F569945E31 ON test_entity8 (badseven_id);",
        "CREATE TABLE generic_entity (id INTEGER NOT NULL, fluff VARCHAR(60) DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE test_entity3 (id INTEGER NOT NULL, entity2_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));",
        "CREATE INDEX IDX_F2F49B7DD1828A49 ON test_entity3 (entity2_id);",
        "CREATE TABLE test_entity10 (id INTEGER NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE ten__nine (ten_id INTEGER NOT NULL, nine_id INTEGER NOT NULL, PRIMARY KEY(ten_id, nine_id));",
        "CREATE INDEX IDX_15065E49325A8A5B ON ten__nine (ten_id);",
        "CREATE INDEX IDX_15065E49DAE4646B ON ten__nine (nine_id);",
        "CREATE TABLE test_entity2 (id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE partial (id INTEGER NOT NULL, json CLOB NOT NULL, class VARCHAR(255) DEFAULT NULL, app_user CLOB DEFAULT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE log (id INTEGER NOT NULL, type_id INTEGER DEFAULT NULL, class VARCHAR(255) DEFAULT NULL, method VARCHAR(255) DEFAULT NULL, json CLOB NOT NULL, eid INTEGER NOT NULL, updated DATETIME NOT NULL, app_user CLOB DEFAULT NULL, PRIMARY KEY(id));",
        "CREATE INDEX IDX_8F3F68C5C54C8C93 ON log (type_id);",
        "CREATE TABLE ledger (id INTEGER NOT NULL, type_id INTEGER DEFAULT NULL, eid INTEGER NOT NULL, updated DATETIME NOT NULL, app_user CLOB DEFAULT NULL, PRIMARY KEY(id));",
        "CREATE INDEX IDX_C07BA4BCC54C8C93 ON ledger (type_id);",
        "CREATE TABLE log_type (id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE player (id INTEGER NOT NULL, game_id INTEGER DEFAULT NULL, location_id INTEGER DEFAULT NULL, mission_id INTEGER DEFAULT NULL, sheep INTEGER DEFAULT NULL, dogs INTEGER DEFAULT NULL, pigs INTEGER DEFAULT NULL, current BOOLEAN DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));",
        "CREATE INDEX IDX_98197A65E48FD905 ON player (game_id);",
        "CREATE INDEX IDX_98197A6564D218E ON player (location_id);",
        "CREATE INDEX IDX_98197A65BE6CAE90 ON player (mission_id);",
        "CREATE TABLE game (id INTEGER NOT NULL, description CLOB NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE eigenfunction (id INTEGER NOT NULL, wave_id INTEGER DEFAULT NULL, trigger VARCHAR(255) DEFAULT NULL, scoring VARCHAR(255) DEFAULT NULL, description CLOB NOT NULL, PRIMARY KEY(id));",
        "CREATE INDEX IDX_DC5FA6BB9461E358 ON eigenfunction (wave_id);",
        "CREATE TABLE eigenfunction__eigenfunction (next_id INTEGER NOT NULL, prev_id INTEGER NOT NULL, PRIMARY KEY(next_id, prev_id));",
        "CREATE INDEX IDX_323B0A2BAA23F6C8 ON eigenfunction__eigenfunction (next_id);",
        "CREATE INDEX IDX_323B0A2BB168B8C0 ON eigenfunction__eigenfunction (prev_id);",
        "CREATE TABLE initial_state (id INTEGER NOT NULL, eigenfunction_id INTEGER DEFAULT NULL, sheep INTEGER DEFAULT NULL, dogs INTEGER DEFAULT NULL, pigs INTEGER DEFAULT NULL, resolved BOOLEAN DEFAULT NULL, closed BOOLEAN DEFAULT NULL, triggered BOOLEAN DEFAULT NULL, PRIMARY KEY(id));",
        "CREATE INDEX IDX_ABB48AF2ACC38317 ON initial_state (eigenfunction_id);",
        "CREATE TABLE wave (id INTEGER NOT NULL, position INTEGER DEFAULT NULL, align INTEGER DEFAULT NULL, description CLOB NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE state (id INTEGER NOT NULL, game_id INTEGER DEFAULT NULL, eigenfunction_id INTEGER DEFAULT NULL, sheep INTEGER NOT NULL, dogs INTEGER NOT NULL, pigs INTEGER NOT NULL, resolved BOOLEAN NOT NULL, closed BOOLEAN NOT NULL, triggered BOOLEAN NOT NULL, PRIMARY KEY(id));",
        "CREATE INDEX IDX_A393D2FBE48FD905 ON state (game_id);",
        "CREATE INDEX IDX_A393D2FBACC38317 ON state (eigenfunction_id);",
        "CREATE TABLE state__state (next_id INTEGER NOT NULL, prev_id INTEGER NOT NULL, PRIMARY KEY(next_id, prev_id));",
        "CREATE INDEX IDX_206FE1C8AA23F6C8 ON state__state (next_id);",
        "CREATE INDEX IDX_206FE1C8B168B8C0 ON state__state (prev_id);",
        "CREATE TABLE mission (id INTEGER NOT NULL, lambs INTEGER DEFAULT NULL, puppies INTEGER DEFAULT NULL, piglets INTEGER DEFAULT NULL, sheep INTEGER DEFAULT NULL, dogs INTEGER DEFAULT NULL, pigs INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE app_role (id INTEGER NOT NULL, role VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, description CLOB NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE app_user (id INTEGER NOT NULL, username VARCHAR(60) NOT NULL, password VARCHAR(255) NOT NULL, salt VARCHAR(255) NOT NULL, email VARCHAR(60) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id));",
        "CREATE UNIQUE INDEX UNIQ_88BDF3E9F85E0677 ON app_user (username);",
        "CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email);",
        "CREATE TABLE app_user__app_role (app_user_id INTEGER NOT NULL, app_role_id INTEGER NOT NULL, PRIMARY KEY(app_user_id, app_role_id));",
        "CREATE INDEX IDX_A39DF5B04A3353D8 ON app_user__app_role (app_user_id);",
        "CREATE INDEX IDX_A39DF5B03B5EA2E1 ON app_user__app_role (app_role_id);",
        "CREATE TABLE app_user__app_group (app_user_id INTEGER NOT NULL, app_group_id INTEGER NOT NULL, PRIMARY KEY(app_user_id, app_group_id));",
        "CREATE INDEX IDX_B328B704A3353D8 ON app_user__app_group (app_user_id);",
        "CREATE INDEX IDX_B328B70F6D4B9EA ON app_user__app_group (app_group_id);",
        "CREATE TABLE login_data (id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, ip VARCHAR(255) NOT NULL, updated DATETIME NOT NULL, username VARCHAR(255) DEFAULT NULL, success BOOLEAN NOT NULL, PRIMARY KEY(id));",
        "CREATE INDEX IDX_6B817826A76ED395 ON login_data (user_id);",
        "CREATE TABLE app_group (id INTEGER NOT NULL, active BOOLEAN NOT NULL, description CLOB NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));",
        "CREATE TABLE supergroup__subgroup (subgroup_id INTEGER NOT NULL, supergroup_id INTEGER NOT NULL, PRIMARY KEY(subgroup_id, supergroup_id));",
        "CREATE INDEX IDX_11CCA93AF5C464CE ON supergroup__subgroup (subgroup_id);",
        "CREATE INDEX IDX_11CCA93A386CD096 ON supergroup__subgroup (supergroup_id);",

    ];
}
